package com.example.batch;


import org.junit.jupiter.api.*;
import org.springframework.batch.test.JobLauncherTestUtils;
import org.springframework.batch.test.context.SpringBatchTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.TestPropertySource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.batch.core.JobParametersBuilder;
import java.nio.file.*;

@SpringBootTest
//@Import(TestBatchConfig.class)
@SpringBatchTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.ANY)
@TestPropertySource(properties = {"app.output.dir=${java.io.tmpdir}/facturas-test-output"})
public class ExtractInvoicesJobTest {

    @Autowired
    private JobLauncherTestUtils jobLauncherTestUtils;

    @Autowired
    private JdbcTemplate jdbcTemplate;


    @Value("${app.output.dir}")
    private String outputDir;

    @BeforeEach
    public void setup() {
        jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS facturas (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "codigo_de_proveedor VARCHAR(7)," +
                "codigo_de_factura VARCHAR(20)," +
                "importe DECIMAL(15,2)," +
                "divisa VARCHAR(3)," +
                "fecha_de_vencimiento DATE," +
                "estado VARCHAR(20)," +
                "extraccion_pago INTEGER," +
                "iban VARCHAR(30))");

        jdbcTemplate.update("DELETE FROM facturas");
        jdbcTemplate.update("INSERT INTO facturas VALUES (?,?,?,?,?,?,?,?,?)",
                1,"PROV001","FACT001",100.00,"EUR",java.sql.Date.valueOf("2023-03-15"),"Pendiente",0,"valor1");
        jdbcTemplate.update("INSERT INTO facturas VALUES (?,?,?,?,?,?,?,?,?)",
                2,"PROV002","FACT002",200.00,"USD",java.sql.Date.valueOf("2023-03-16"),"Pendiente",0,"valor2");
    }

    @Test
    public void testJobExtractsAndUpdates() throws Exception {

        String fecha = "2023-03-15";

        JobParametersBuilder builder = new JobParametersBuilder();
        builder.addString("fecha", fecha);
        builder.addLong("time", System.currentTimeMillis());

        var jobExecution = jobLauncherTestUtils.launchJob(builder.toJobParameters());

        Assertions.assertEquals(org.springframework.batch.core.BatchStatus.COMPLETED, jobExecution.getStatus());

        // Check file exists
        Path out = Paths.get(outputDir + "/invoices_" + fecha + ".csv");
        Assertions.assertTrue(Files.exists(out), "Fichero de salida no encontrado: " + out.toString());

        // Check DB updated
        Integer extraccion = jdbcTemplate.queryForObject(
                "SELECT extraccion_pago FROM facturas WHERE codigo_de_factura = ?",
                Integer.class, "FACT001");
        Assertions.assertEquals(1, extraccion);
    }
}

