spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  datasource:
    url: jdbc:h2:mem:facturasdb;DB_CLOSE_DELAY=-1;MODE=Oracle
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
  batch:
    jdbc:
      initialize-schema: always

app:
  output:
    dir: ./output

#logging:
#  level:
#    org.springframework.boot: DEBUG
