CREATE TABLE facturas (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_de_proveedor   VARCHAR2(7),
  codigo_de_factura     VARCHAR2(20),
  importe               NUMBER(15,2),
  divisa                VARCHAR2(3),
  fecha_de_vencimiento  DATE,
  estado                VARCHAR2(20),
  extraccion_pago       NUMBER(1),
  iban                  VARCHAR2(30)
);
